<?php

class EmailTemplateSeeder extends Seeder {

    private $table = 'email_templates';

    public function run() {
        $this->db->truncate($this->table);
        
        //seed records manually
        echo 'seeding'  .$this->table;
        $this->db->query("INSERT INTO `email_templates` (`iEmailTemplateId`, `vEmailCode`, `vFromName`, `vFromEmail`, `vEmailSubject`, `tEmailMessage`, `dtCreatedDateTime`, `dtUpdatedDateTime`, `eStatus`) VALUES
(1, 'WELCOME_MESSAGE', 'Bizeazy', 'demo1.testing1@gmail.com', 'Welcome in Bizeazy', '', '2018-01-12 14:51:27', '2018-01-29 19:32:27', 'None'),
(2, 'LINK', 'Bizeazy', 'demo1.testing1@gmail.com', 'Forgot Password', '<html xmlns=http://www.w3.org/1999/xhtml>\n<head>\n<meta name=viewport content=width=device-width />\n<meta http-equiv=Content-Type content=text/html; charset=UTF-8 />\n<title>Email</title>\n</head>\n<body bgcolor=#FFFFFF>\n<table width=96% border=0 cellspacing=0 cellpadding=0 bgcolor=#f2f5f7 style=padding:1% 2% 1% 2%;margin:0 0 0 2%;border-radius:10px>\n<tr>\n<td>\n<table width=100% border=0 cellspacing=0 cellpadding=0>\n<tr>\n<td>\n<table width=100% border=0 cellspacing=0 cellpadding=0 style=border-radius:5px!important;padding:10px 0!important;background:#ED5C5D>\n<tr>\n<td align=center valign=middle><img src=#EMAIL_LOGO# alt=Bizeazy style=width: 100px;padding:10px 0>  </td>\n</tr>\n</table>\n</td>\n</tr>\n<tr>\n<td>\n<table width=100% border=0 cellspacing=0 cellpadding=0 style=margin-bottom:20px>\n<tr>\n<td style=font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#000;padding:32px 0 10px 10px>Hello #USERNAME#,</td>\n</tr>\n<tr>\n<td style=font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#000;padding:10px 0 10px 10px>Welcome to Bizeazy,</td>\n</tr>\n\n<tr>\n<td style=font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#000;padding:10px 0 10px 10px> Please Click here <a href=#LINK#>#LINK#</a></td>\n</tr>\n<tr>\n<td style=font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#000;padding:10px 0 0 10px>Kind Regards,<br/> Bizeazy</td>\n</tr>\n</table>\n</td>\n</tr>\n</table>\n</td>\n</tr>\n<tr>\n<td style=background:#ED5C5D;border-radius:3px>&nbsp;</td>\n</tr>\n</table>\n</body>\n</html>', '2018-06-15 14:51:27', '2018-06-15 19:32:27', 'None'),
(3, 'THANKS', 'Bizeazy', 'demo1.testing1@gmail.com', 'Thanks For Contact me', '<meta name=viewport content=width=device-width /><meta http-equiv=Content-Type content=text/html; charset=UTF-8 />\r\n<title></title>\r\n<table bgcolor=#f2f5f7 border=0 cellpadding=0 cellspacing=0 style=padding:1% 2% 1% 2%;margin:0 0 0 2%;border-radius:10px width=96%>\r\n	<tbody>\r\n		<tr>\r\n			<td>\r\n			<table border=0 cellpadding=0 cellspacing=0 width=100%>\r\n				<tbody>\r\n					<tr>\r\n						<td>\r\n						<table border=0 cellpadding=0 cellspacing=0 style=border-radius:5px!important;padding:10px 0!important;background:#e75555 width=100%>\r\n							<tbody>\r\n								<tr>\r\n									<td align=center valign=middle><img alt=Bizeazy src=#EMAIL_LOGO# style=width:100px; /></td>\r\n								</tr>\r\n							</tbody>\r\n						</table>\r\n						</td>\r\n					</tr>\r\n					<tr>\r\n						<td>\r\n						<table border=0 cellpadding=0 cellspacing=0 style=margin-bottom:20px width=100%>\r\n							<tbody>\r\n								<tr>\r\n									<td style=font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#000;padding:32px 0 10px 10px>Dear #USERNAME#,</td>\r\n								</tr>\r\n								<tr>\r\n									<td style=font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#000;padding:10px 0 10px 10px>#MESSAGE#</td>\r\n								</tr>\r\n								<tr>\r\n									<td style=font-family:Arial,Helvetica,sans-serif;font-size:13px;color:#000;padding:10px 0 0 10px>Kind Regards,<br />\r\n									Bizeazy Support Team</td>\r\n								</tr>\r\n							</tbody>\r\n						</table>\r\n						</td>\r\n					</tr>\r\n				</tbody>\r\n			</table>\r\n			</td>\r\n		</tr>\r\n		<tr>\r\n			<td style=background:#e75555;border-radius:3px>&nbsp;</td>\r\n		</tr>\r\n	</tbody>\r\n</table>\r\n', '2018-06-18 14:51:27', '2018-06-18 19:32:27', 'None');");
        echo PHP_EOL;
    }
}
